### ISSUE TITLE
Finish setting up the TulipaIO.jl repo

### ISSUE THREAD

**Issue by suvayu** [TulipaEnergy/TulipaIO.jl#21]
## Tasks

- [x] #39
- [x] Protect main branch
- [x] Register package (https://github.com/JuliaRegistries/General/pull/106391) check in 11/May in the afternoon.
- [x] #41
  - [x] #25

---

Sorry about delaying this.  I finished all the tasks upto (4) on this [list](https://github.com/abelsiqueira/COPIERTemplate.jl/?tab=readme-ov-file#how-to-install). (5) & (6) requires admin privileges. Can someone take care of this?

cc: @clizbe?

**Comment by clizbe** [comment]
@suvayu I think I completed 5 & 6 successfully. :)

**Comment by suvayu** [comment]
Great! Let's see if the next [CopierUpdate](https://github.com/TulipaEnergy/TulipaIO.jl/actions/workflows/Copier.yml) job fails :-p before closing this issue

**Comment by clizbe** [comment]
- [ ] Fix copier template
- [ ] Protect main branch
- [ ] Register package
- [ ] Anything else? Write this stuff down.

**Comment by abelsiqueira** [comment]
The package is registered now.
