### ISSUE TITLE
COMPETES import scripts

### ISSUE THREAD

**Issue by clizbe** [TulipaEnergy/TulipaIO.jl#30]
## Tasks

- [x] [Imported to SQLite](https://github.com/TulipaEnergy/competes-pipeline)
- [x] Recipe to attach SQLite db to DuckDB
  - Optionally, if necessary, may convert to native DuckDB
- [ ] Scripts to convert tables to what Tulipa expects

## Export MS Access db to SQlite

This works on Linux (so also works on Windows WSL):

1. Install `mdbtools` & `sqlite-tools` (optional)
2. Then in the shell (bash)
   ```shell
   mdb-schema /path/to/ms-access.mdb > schema.sql
   sqlite3 /path/to/sqlite-copy.db < schema.sql
   for tbl in $(IFS=$'\n' mdb-tables -1 /path/to/ms-access.mdb); do
     {
         mdb-export /path/to/ms-access.mdb "$tbl" | \
           sqlite-utils insert -c /path/to/sqlite-copy.db "$tbl" - ;
     } && echo "'$tbl' exported";
   done
   ``` 

## Reading from DuckDB

See [SQLite import](https://duckdb.org/docs/guides/database_integration/sqlite)

```sql
INSTALL sqlite;
ATTACH 'sqlite-copy.db' AS competes (TYPE sqlite);
USE competes;
SHOW TABLES;
```

**Comment by nope82** [comment]
Need to update the instructions in the shell to fix the blank spaces from the tables' headers to export the .mdb file to .db
Additionally, test with one more windows user the connection of the resulting .db to duckdb in WSL, and update readme accordingly

**Comment by clizbe** [comment]
Are these things you guys are going to work on, or something you need help with? If so, from whom?
